version: '3'
services:
#mssql docker
  farmcommerce-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    expose:
        - 1433
    networks:
      - farmcommercenet2023

  farmcommerce-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=farmcommerce-sql,1433;Database=FarmCommerce;User=sa;Password=QWElkj132!;ConnectRetryCount=0; TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 7121:7121
    networks:
      - farmcommercenet2023
    links:
      - farmcommerce-sql
    depends_on:
      - farmcommerce-sql
      
networks:
  farmcommercenet2023:
    driver: bridge      